# This docker file builds image by only copying pre-build files 
# To use this, build public_html before building docker image.
# To build image by using docker container, use Dockerfile instead.
FROM nginx
COPY public_html /usr/share/nginx/html
