/* 
 * The MIT License
 *
 * Copyright 201 sz2.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

export enum AssettoCorsaSHMPhysicsParameterCode
{
    Gas,
    Brake,
    Fuel,
    Gear,
    Rpms,
    SteerAngle,
    SpeedKmh,
    Velocity,
    AccG,
    WheelSlip,
    WheelLoad,
    WheelsPressure,
    WheelAngularSpeed,
    TyreWear,
    TyreDirtyLevel,
    TyreCoreTemperature,
    CamberRad,
    SuspensionTravel,
    Drs,
    TC,
    Heading,
    Pitch,
    Roll,
    CgHeight,
    CarDamage,
    NumberOfTyresOut,
    PitLimiterOn,
    Abs,
    KersCharge,
    KersInput,
    AutoShifterOn,
    RideHeight,
    TurboBoost,
    Ballast,
    AirDensity,
    AirTemp,
    RoadTemp,
    LocalAngularVelocity,
    FinalFF,
    PerformanceMeter,
    EngineBrake,
    ErsRecoveryLevel,
    ErsPowerLevel,
    ErsHeatCharging,
    ErsisCharging,
    KersCurrentKJ,
    DrsAvailable,
    DrsEnabled,
    BrakeTemp,
    Clutch,
    TyreTempI,
    TyreTempM,
    TyreTempO,
    IsAIControlled,
    TyreContactPoint,
    TyreContactNormal,
    TyreContactHeading,
    BrakeBias,
    LocalVelocity,

    //Custom parameter code
    ManifoldPressure
}

export enum AssettoCorsaSHMGraphicsParameterCode
{
    Status,
    Session,
    CurrentTime,
    LastTime,
    BestTime,
    Split,
    CompletedLaps,
    Position,
    iCurrentTime,
    iLastTime,
    iBestTime,
    SessionTimeLeft,
    DistanceTraveled,
    IsInPit,
    CurrentSectorIndex,
    LastSectorTime,
    NumberOfLaps,
    TyreCompound,
    ReplayTimeMultiplier,
    NormalizedCarPosition,
    CarCoordinates,
    PenaltyTime,
    Flag,
    IdealLineOn,
    IsInPitLane,
    SurfaceGrip,
    MandatoryPitDone
}

export enum AssettoCorsaSHMStaticInfoParameterCode
{
    SMVersion,
    ACVersion,
    NumberOfSessions,
    NumCars,
    CarModel,
    Track,
    PlayerName,
    PlayerSurname,
    PlayerNick,
    SectorCount,
    MaxTorque,
    MaxPower,
    MaxRpm,
    MaxFuel,
    SuspensionMaxTravel,
    TyreRadius,
    MaxTurboBoost,
    PenaltiesEnabled,
    AidFuelRate,
    AidTireRate,
    AidMechanicalDamage,
    AidAllowTyreBlankets,
    AidStability,
    AidAutoClutch,
    AidAutoBlip,
    HasDRS,
    HasERS,
    HasKERS,
    KersMaxJoules,
    EngineBrakeSettingsCount,
    ErsPowerControllerCount,
    TrackSPlineLength,
    TrackConfiguration,
    ErsMaxJ,
    IsTimedRace,
    HasExtraLap,
    CarSkin,
    ReversedGridPositions,
    PitWindowStart,
    PitWindowEnd
}

export enum AssettoCorsaSHMStringVALCode
{
    Status,
    Session,
    CurrentTime,
    LastTime,
    BestTime,
    Split,
    
    TyreCompound,

    Flag,

    SMVersion,
    ACVersion,

    CarModel,
    Track,
    PlayerName,
    PlayerSurname,
    PlayerNick,

    TrackConfiguration,

    CarSkin
}

export enum AssettoCorsaSHMNumericalVALCode
{
    Gas,
    Brake,
    Fuel,
    Gear,
    Rpms,
    SteerAngle,
    SpeedKmh,
    Velocity_00,
    Velocity_01,
    Velocity_02,
    AccG_00,
    AccG_01,
    AccG_02,
    WheelSlip_00,
    WheelSlip_01,
    WheelSlip_02,
    WheelSlip_03,
    WheelLoad_00,
    WheelLoad_01,
    WheelLoad_02,
    WheelLoad_03,
    WheelsPressure_00,
    WheelsPressure_01,
    WheelsPressure_02,
    WheelsPressure_03,
    WheelAngularSpeed_00,
    WheelAngularSpeed_01,
    WheelAngularSpeed_02,
    WheelAngularSpeed_03,
    TyreWear_00,
    TyreWear_01,
    TyreWear_02,
    TyreWear_03,
    TyreDirtyLevel_00,
    TyreDirtyLevel_01,
    TyreDirtyLevel_02,
    TyreDirtyLevel_03,
    TyreCoreTemperature_00,
    TyreCoreTemperature_01,
    TyreCoreTemperature_02,
    TyreCoreTemperature_03,
    CamberRad_00,
    CamberRad_01,
    CamberRad_02,
    CamberRad_03,
    SuspensionTravel_00,
    SuspensionTravel_01,
    SuspensionTravel_02,
    SuspensionTravel_03,    
    Drs,
    TC,
    Heading,
    Pitch,
    Roll,
    CgHeight,
    CarDamage_00,
    CarDamage_01,
    CarDamage_02,
    CarDamage_03,
    CarDamage_04,
    NumberOfTyresOut,
    PitLimiterOn,
    Abs,
    KersCharge,
    KersInput,
    AutoShifterOn,
    RideHeight_00,
    RideHeight_01,
    TurboBoost,
    Ballast,
    AirDensity,
    AirTemp,
    RoadTemp,
    LocalAngularVelocity_00,
    LocalAngularVelocity_01,
    LocalAngularVelocity_02,
    FinalFF,
    PerformanceMeter,
    EngineBrake,
    ErsRecoveryLevel,
    ErsPowerLevel,
    ErsHeatCharging,
    ErsisCharging,
    KersCurrentKJ,
    DrsAvailable,
    DrsEnabled,
    BrakeTemp_00,
    BrakeTemp_01,
    BrakeTemp_02,
    BrakeTemp_03,
    Clutch,
    TyreTempI_00,
    TyreTempI_01,
    TyreTempI_02,
    TyreTempI_03,
    TyreTempM_00,
    TyreTempM_01,
    TyreTempM_02,
    TyreTempM_03,
    TyreTempO_00,
    TyreTempO_01,
    TyreTempO_02,
    TyreTempO_03,    
    IsAIControlled,
    TyreContactPoint_00_X,
    TyreContactPoint_01_X,
    TyreContactPoint_02_X,
    TyreContactPoint_03_X,
    TyreContactPoint_00_Y,
    TyreContactPoint_01_Y,
    TyreContactPoint_02_Y,
    TyreContactPoint_03_Y,
    TyreContactPoint_00_Z,
    TyreContactPoint_01_Z,
    TyreContactPoint_02_Z,
    TyreContactPoint_03_Z,
    TyreContactNormal_00_X,
    TyreContactNormal_01_X,
    TyreContactNormal_02_X,
    TyreContactNormal_03_X,
    TyreContactNormal_00_Y,
    TyreContactNormal_01_Y,
    TyreContactNormal_02_Y,
    TyreContactNormal_03_Y,
    TyreContactNormal_00_Z,
    TyreContactNormal_01_Z,
    TyreContactNormal_02_Z,
    TyreContactNormal_03_Z,
    TyreContactHeading_00_X,
    TyreContactHeading_01_X,
    TyreContactHeading_02_X,
    TyreContactHeading_03_X,
    TyreContactHeading_00_Y,
    TyreContactHeading_01_Y,
    TyreContactHeading_02_Y,
    TyreContactHeading_03_Y,
    TyreContactHeading_00_Z,
    TyreContactHeading_01_Z,
    TyreContactHeading_02_Z,
    TyreContactHeading_03_Z,    
    BrakeBias,
    LocalVelocity_00,
    LocalVelocity_01,
    LocalVelocity_02,

    //Custom parameter code
    ManifoldPressure,

    CompletedLaps,
    Position,
    iCurrentTime,
    iLastTime,
    iBestTime,
    SessionTimeLeft,
    DistanceTraveled,
    IsInPit,
    CurrentSectorIndex,
    LastSectorTime,
    NumberOfLaps,
    ReplayTimeMultiplier,
    NormalizedCarPosition,
    CarCoordinates_00,
    CarCoordinates_01,
    CarCoordinates_02,
    PenaltyTime,

    IdealLineOn,
    IsInPitLane,
    SurfaceGrip,
    MandatoryPitDone,

    NumberOfSessions,
    NumCars,

    SectorCount,
    MaxTorque,
    MaxPower,
    MaxRpm,
    MaxFuel,
    SuspensionMaxTravel_00,
    SuspensionMaxTravel_01,
    SuspensionMaxTravel_02,
    SuspensionMaxTravel_03,
    TyreRadius_00,
    TyreRadius_01,
    TyreRadius_02,
    TyreRadius_03,   
    MaxTurboBoost,
    PenaltiesEnabled,
    AidFuelRate,
    AidTireRate,
    AidMechanicalDamage,
    AidAllowTyreBlankets,
    AidStability,
    AidAutoClutch,
    AidAutoBlip,
    HasDRS,
    HasERS,
    HasKERS,
    KersMaxJoules,
    EngineBrakeSettingsCount,
    ErsPowerControllerCount,
    TrackSPlineLength,

    ErsMaxJ,
    IsTimedRace,
    HasExtraLap,

    ReversedGridPositions,
    PitWindowStart,
    PitWindowEnd
}
